include:
  - path: 'common/docker-compose.networks.yml'
  - path: 'traefik/docker-compose.traefik.yml'
#  - path: 'portainer/docker-compose.portainer.yml'
  - path: 'nextcloud/docker-compose.nextcloud.yml'