services:
  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION:-latest}
    container_name: traefik
    restart: always
    networks:
      - proxy-external
    ports:
      - ${TRAEFIK_UNSECURED_ENTRYPOINT:-80}:80
      - ${TRAEFIK_SECURED_ENTRYPOINT:-443}:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${GLOBAL_DOCKER_DATA_PATH:-/docker/apps}/traefik/:/etc/traefik
    command:
      #provider
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=proxy-external'
      #logs
      - '--log.level=${TRAEFIK_LOG_LEVEL}'
      - '--log.filepath=/etc/traefik/logs/traefik.log'
      - '--log.format=json'
      - '--accesslog.filepath=/etc/traefik/logs/access.log'
      - '--accesslog.format=json'
      #misc
      - '--api.dashboard=true'
      #entrypoints
      - '--entrypoints.http.address=:${TRAEFIK_UNSECURED_ENTRYPOINT:-80}'
      - '--entrypoints.https.address=:${TRAEFIK_SECURED_ENTRYPOINT:-443}'
      #SSL
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.letsencrypt.acme.caserver=${TRAEFIK_ACME_CASERVER:-changeme}'
      - '--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-changeme@example.org}'
      - '--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/letsencrypt/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53'
    environment:
      - CF_API_EMAIL=${TRAEFIK_CF_ADMIN_EMAIL:-changeme@example.org}
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN:-changeme}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.dashboard.basicauth.users=${TRAEFIK_AUTH_USERS}'
      - 'traefik.http.routers.traefik.entrypoints=http'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.${GLOBAL_SITE_NAME:-localhost}`)'
      - 'traefik.http.routers.traefik.middlewares=traefik-https-redirect'
      - 'traefik.http.routers.traefik-secure.tls=true'
      - 'traefik.http.routers.traefik-secure.entrypoints=https'
      - 'traefik.http.routers.traefik-secure.rule=Host(`traefik.${GLOBAL_SITE_NAME:-localhost}`)'
      - 'traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].main=${TRAEFIK_TOP_LEVEL_DOMAIN:-example.org}'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${TRAEFIK_TOP_LEVEL_DOMAIN:-example.org}'
      - 'traefik.http.routers.traefik-secure.service=api@internal'
      - 'traefik.http.routers.traefik-secure.middlewares=dashboard@docker'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'