services:
  nextcloud-db:
    image: mariadb:${NEXTCLOUD_MARIADB_VERSION:-latest}
    container_name: nextcloud-db
    restart: always
    networks:
      - nextcloud-internal
    volumes:
      - ${GLOBAL_DOCKER_DATA_PATH}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MARIADB_ROOT_PASSWORD:-nextcloud}
      - MYSQL_DATABASE=${NEXTCLOUD_MARIADB_DBNAME:-nextcloud}
      - MYSQL_USER=${NEXTCLOUD_MARIADB_USER:-nextcloud}
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_DB_PASSWORD:-nextcloud}
    command: 
      --transaction-isolation=READ-COMMITTED 
      --log-bin=ROW 
      --skip-innodb-read-only-compressed
    labels:
      - traefik.enable=false
  
  nextcloud-redis:
    image: redis:${NEXTCLOUD_REDIS_VERSION:-latest}
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: always
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASSWORD:-nextcloud} # REPLACE WITH REDIS PASSWORD
    networks:
      - nextcloud-internal
  
  nextcloud-app:
    image: nextcloud:${NEXTCLOUD_APP_VERSION:-latest}
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-internal
      - proxy-external
    volumes:
      - ${GLOBAL_DOCKER_DATA_PATH:-/docker/apps}/nextcloud/app:/var/www/html
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${NEXTCLOUD_REDIS_PASSWORD:-nextcloud}
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=${NEXTCLOUD_MARIADB_DBNAME:-nextcloud}
      - MYSQL_USER=${NEXTCLOUD_MARIADB_USER:-nextcloud}
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_DB_PASSWORD:-nextcloud}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://mycloud.${GLOBAL_SITE_NAME:-localhost}
    labels:
      - 'traefik.enable=true'
      # https://docs.nextcloud.com/server/22/admin_manual/installation/harden_server.html
      # https://doc.traefik.io/traefik/v2.6/middlewares/http/headers/
      - 'traefik.http.middlewares.nextcloud-header.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.customFrameOptionsValue=SAMEORIGIN'
      - 'traefik.http.middlewares.nextcloud-header.headers.customResponseHeaders.Strict-Transport-Security=15552000'
      - 'traefik.http.middlewares.nextcloud-header.headers.referrerPolicy=no-referrer'
      - 'traefik.http.middlewares.nextcloud-header.headers.stsincludesubdomains=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.stspreload=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.stsseconds=15552000'
      - 'traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.permanent=true'
      # https://docs.nextcloud.com/server/21/admin_manual/issues/general_troubleshooting.html#service-discovery
      # https://docs.nextcloud.com/server/23/admin_manual/configuration_server/reverse_proxy_configuration.html#traefik-2
      # https://doc.traefik.io/traefik/v2.6/middlewares/http/redirectregex/
      - 'traefik.http.middlewares.nextcloud-redirect-dav.redirectRegex.permanent=true'
      - 'traefik.http.middlewares.nextcloud-redirect-dav.redirectRegex.regex=https://mycloud.${GLOBAL_SITE_NAME:-localhost}/.well-known/(card|cal)dav'
      - 'traefik.http.middlewares.nextcloud-redirect-dav.redirectRegex.replacement=https://mycloud.${GLOBAL_SITE_NAME:-localhost}/remote.php/dav/'
      - 'traefik.http.routers.nextcloud.entrypoints=https'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.nextcloud.middlewares=nextcloud-header,nextcloud-redirect-dav,traefik-https-redirect'
      - 'traefik.http.routers.nextcloud.rule=Host(`mycloud.${GLOBAL_SITE_NAME:-localhost}`)'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
      - 'traefik.http.services.nextcloud.loadbalancer.passHostHeader=true'
